# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 13) do

  create_table "configurations", :force => true do |t|
    t.column "puzzle_id",         :integer
    t.column "name",              :string
    t.column "default_thumbnail", :string
    t.column "default_picture",   :string
    t.column "price",             :decimal, :precision => 5, :scale => 2, :default => 0.0
    t.column "active",            :boolean
    t.column "out_of_stock",      :boolean
    t.column "on_sale",           :boolean,                               :default => false
  end

  create_table "customer_stories", :force => true do |t|
    t.column "customer_name", :string
    t.column "story",         :text
    t.column "active",        :boolean
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
  end

  create_table "email_messages", :force => true do |t|
    t.column "from_email", :string
    t.column "subject",    :string
    t.column "message",    :text
    t.column "name",       :string
  end

  create_table "entries", :force => true do |t|
    t.column "name",    :string
    t.column "address", :string
    t.column "city",    :string
    t.column "state",   :string
    t.column "zip",     :string
    t.column "phone",   :string
    t.column "email",   :string
    t.column "month",   :string
  end

  create_table "puzzles", :force => true do |t|
    t.column "name",                  :string
    t.column "description",           :string
    t.column "size",                  :string
    t.column "active",                :boolean
    t.column "default_configuration", :integer
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

end
