# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 10) do

  create_table "configurations", :force => true do |t|
    t.column "puzzle_id",         :integer
    t.column "name",              :string
    t.column "default_thumbnail", :string
    t.column "default_picture",   :string
    t.column "price",             :decimal, :precision => 5, :scale => 2, :default => 0.0
    t.column "active",            :boolean
    t.column "out_of_stock",      :boolean
  end

  create_table "customer_stories", :force => true do |t|
    t.column "customer_name", :string
    t.column "story",         :text
    t.column "active",        :boolean
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
  end

  create_table "email_messages", :force => true do |t|
    t.column "from_email", :string
    t.column "subject",    :string
    t.column "message",    :text
    t.column "name",       :string
  end

  create_table "products", :force => true do |t|
    t.column "name",              :string
    t.column "description",       :string
    t.column "price",             :decimal, :precision => 5, :scale => 2, :default => 0.0
    t.column "default_thumbnail", :string
    t.column "default_picture",   :string
    t.column "size",              :string
    t.column "active",            :boolean
    t.column "default_colored",   :string
    t.column "unfinished_price",  :decimal, :precision => 5, :scale => 2
  end

  create_table "puzzles", :force => true do |t|
    t.column "name",                  :string
    t.column "description",           :string
    t.column "size",                  :string
    t.column "active",                :boolean
    t.column "default_configuration", :integer
  end

end
